### ISSUE TITLE
Trailing / on some of the URL's in the CSV

### ISSUE THREAD

**Issue by GambitC90** [MHimken/toolbox#3]
I don't think there is supposed to be a / in these host names in the INRCustomList.csv.

"activation-v2.sls.microsoft.com/", 443, TCP, 9991
"validation-v2.sls.microsoft.com/", 443, TCP, 9991
"displaycatalog.mp.microsoft.com/", 443, TCP, 9991

**Comment by GambitC90** [comment]
Created pull request for this.

**Comment by MHimken** [comment]
Merged - thanks for your contribution!
