### ISSUE TITLE
Updated Domains

### ISSUE THREAD

**Issue by mantis** [MHimken/toolbox#5]
Hi,

The domain list in the script isn't up to date with the latest update:

https://github.com/MicrosoftDocs/memdocs/commit/d5021ef84ba592f1bb2e579498aa24efb50fc172

**Comment by MHimken** [comment]
True, the *emdl* addresses got removed. The other addresses around `do.dsp.mp.microsoft.com` and `dl.delivery.mp.microsoft.com` are still valid as they add more precise (and working) domains. Thanks for flagging! Update here: https://github.com/MHimken/toolbox/commit/e7752ec7f2ff2cfcbb27f1a650f355d535a12bf5
